"""M4 regression: torch vs rust VAE backend.

1. Unit: random latent -> adapter.decode both backends, max err.
2. E2E: 3 tts texts, same seed, compare waveforms + wall time.
3. Smoke: 1 voice_clone (torch streaming path, must still work).
"""
import os
import time

import torch

# --- unit level (no model load) ---
from cutetts.modeling.audio_adapter import AudioAcousticVAEAdapter

VAE_DIR = "model/CuteTTS-distill/weights/audio_vae"

torch.manual_seed(0)
lat = torch.randn(2, 10, 64)  # [B, T, 64], batch=2 covers loop

os.environ["CUTETTS_VAE_BACKEND"] = "torch"
adapter = AudioAcousticVAEAdapter(VAE_DIR)
with torch.no_grad():
    t0 = time.time()
    ref = adapter.decode(lat)
    t_torch = time.time() - t0

os.environ["CUTETTS_VAE_BACKEND"] = "rust"
adapter_r = AudioAcousticVAEAdapter(VAE_DIR)
with torch.no_grad():
    t0 = time.time()
    got = adapter_r.decode(lat)
    t_rust = time.time() - t0

err = (ref - got).abs().max().item()
print(f"unit: torch {t_torch:.2f}s rust {t_rust:.2f}s max_err={err:.2e}")
assert ref.shape == got.shape, (ref.shape, got.shape)
assert err < 1e-4, err

# --- e2e ---
from cutetts import CuteTTS

TEXTS = [
    "The voice generated by this model sounds amazing!",
    "Rust backend decoding is now online.",
    "你好，这是端到端回归测试。",
]

os.environ["CUTETTS_VAE_BACKEND"] = "torch"
m_torch = CuteTTS.from_pretrained("model/CuteTTS-distill", device="cpu")
os.environ["CUTETTS_VAE_BACKEND"] = "rust"
m_rust = CuteTTS.from_pretrained("model/CuteTTS-distill", device="cpu")

for i, text in enumerate(TEXTS):
    t0 = time.time()
    a = m_torch.generate(text, mode="tts", seed=42, show_progress=False)
    dt_torch = time.time() - t0
    t0 = time.time()
    b = m_rust.generate(text, mode="tts", seed=42, show_progress=False)
    dt_rust = time.time() - t0
    n = min(a.waveform.shape[-1], b.waveform.shape[-1])
    e = (a.waveform[..., :n] - b.waveform[..., :n]).abs().max().item()
    print(f"e2e[{i}]: len={n} torch={dt_torch:.1f}s rust={dt_rust:.1f}s max_err={e:.2e}")
    assert e < 1e-3, e

# --- voice_clone smoke (streaming/torch path) ---
c = m_torch.generate(
    "音色克隆冒烟测试。",
    mode="voice_clone",
    reference_audio="assets/default_reference.wav",
    seed=42,
    show_progress=False,
)
print(f"voice_clone smoke ok: {c.waveform.shape[-1]} samples @ {c.sample_rate}Hz")
print("M4 REGRESSION PASSED")
